name: CI

on:
    push:
        branches:
            - main
            - adding-tests
    pull_request:
        branches:
            - main

jobs:
    build-front-end:
        strategy:
            matrix:
                os: ["windows-latest", "macos-latest"]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Build
              run: |
                  cd front-end/vide
                  npm i
                  npm run compile

    build-back-end:
        strategy:
            matrix:
                os: ["windows-latest", "macos-latest"]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "5.0.x"
            - name: Build
              run: |
                  cd back-end
                  dotnet restore
                  dotnet build

    build-and-test-front-end:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install Dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "5.0.x"
            - name: Build
              run: |
                  cd front-end/vide
                  npm i
                  npm run compile
            - name: Test
              run: |
                  cd front-end/vide
                  npm run test

    build-and-test-back-end:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "5.0.x"
            - name: Build
              run: |
                  cd back-end
                  dotnet restore
                  dotnet build
            - name: Test
              run: |
                  cd back-end/Testing
                  dotnet run
